### ISSUE TITLE
Invalid iterator accessed in GraphicsPipelineManager::bake()

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#103]
The problem is located in the following code block (lines 918 to 940 in _graphics_pipeline_manager.cpp_):
```
auto base_bake_item_iterator = std::find(bake_items.begin(),
                                         bake_items.end(),
                                         current_pipeline_base_pipeline_id);

if (base_bake_item_iterator != bake_items.end() )
{
    /* Case 1 */
    graphics_pipeline_create_info.basePipelineHandle = VK_NULL_HANDLE;
    graphics_pipeline_create_info.basePipelineIndex  = static_cast<int32_t>(base_bake_item_iterator - bake_items.begin() );
}
else
if (base_bake_item_iterator->pipeline_ptr                 != nullptr            &&
    base_bake_item_iterator->pipeline_ptr->baked_pipeline != VK_NULL_HANDLE)
{
    /* Case 2 */
    graphics_pipeline_create_info.basePipelineHandle = base_bake_item_iterator->pipeline_ptr->baked_pipeline;
    graphics_pipeline_create_info.basePipelineIndex  = UINT32_MAX;
}
else
{
    /* Case 3 */
    anvil_assert_fail();
}
```
The _if_-condition checks if the iterator _base_bake_item_iterator_ is valid, which means it's invalid in the else branch. However the else-branch attempts to dereference the invalid iterator, resulting in undefined behavior.
The same problem exists in _ComputePipelineManager::bake_.

I've had this happen when trying to create a derived pipeline using _create_derivative_.

**Comment by DominikWitczakAMD** [comment]
Thanks for catching this. I'll be spending some time this week resolving various issues reported for Anvil. Will do my best to address this before EoW.

**Comment by DominikWitczakAMD** [comment]
Fixed internally. Apologies for the delay.
