### ISSUE TITLE
How to use pipeline cache with Anvil?

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#104]
_GraphicsPipelineManager::create_ allows you to specify a custom pipeline cache object, however as far as I can tell, you're not really supposed to use that function, instead you're supposed to use the graphics pipeline manager that's automatically created with the device (_BaseDevice::get_graphics_pipeline_manager_), since that's the one being used in some other functions (e.g. _Anvil::CommandBufferBase::record_bind_pipeline_).

However, the pipeline manager created with the device (_BaseDevice::init_) is always created with an empty pipeline cache. If I wanted to load an existing pipeline cache from the disk, for example, how would I do that? Is that currently not possible?

**Comment by DominikWitczakAMD** [comment]
Yes, it is recommended to reuse the pipeline managers which are created at device instantiation time.

What you discovered is effectively the problem of a missing DeviceCreateInfo structure which would let the application specify, amongst other things, initial pipeline cache contents on a per-manager basis.

I'm putting this on my TODO list. Thanks for spotting this design quirk.

**Comment by DominikWitczakAMD** [comment]
Fixed internally. Anvil::DeviceCreateInfo now exposes a new set_pipeline_cache_ptr() function which lets apps specify which pipeline cache instance should be used for both compute and gfx pipeline cache manager. If none is specified, legacy behavior will kick in (ie. a new dummy pipeline cache will be instantiated).

I'll be pushing this fix early next week.

**Comment by DominikWitczakAMD** [comment]
Fixed in the latest version.

**Comment by Silverlan** [comment]
Hm... How does one use it exactly?
_PipelineCache::create_ requires that you pass a device object as argument. That means you can't create the pipeline cache before you've created the device, but _set_pipeline_cache_ptr_ is a method of _DeviceCreateInfo_, which means the device doesn't exist yet. So how does one create a pipeline cache before creating a device?
