### ISSUE TITLE
Why does PipelineCache::get_data take a void** parameter for data?

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#105]
_PipelineCache::get_data_ takes a _void**_ for the output data, which is then implicitly cast to a _void*_ in the _vkGetPipelineCacheData_-call, that doesn't seem right to me:
```
bool Anvil::PipelineCache::get_data(size_t*      out_n_data_bytes_ptr,
                                    const void** out_data_ptr)
{
    VkResult result_vk;

    result_vk = vkGetPipelineCacheData(m_device_ptr->get_device_vk(),
                                       m_pipeline_cache,
                                       out_n_data_bytes_ptr,
                                       out_data_ptr);

    anvil_assert(result_vk);

    return is_vk_call_successful(result_vk);
}
```
I'm not sure if this is a bug, or if there's some logic behind it I don't understand.

**Comment by Silverlan** [comment]
Something else related I just noticed:
Both _PipelineCache::get_data_ and _PipelineCache::merge_ use _anvil_assert_ to check the _VkResult_, I believe that should be _anvil_assert_vk_call_succeeded_ instead, otherwise it's going to fail the assertion when _VK_SUCCESS_ is returned (since its value is 0), which is probably not intended.

**Comment by DominikWitczakAMD** [comment]
Agreed, this is a shameful piece of nonsensical code :-) I've fixed this internally; will be including the change in the update, hopefully coming tomorrow.
