### ISSUE TITLE
Suggestion: Add CMake option to use SDK location for glslang library

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#118]
A CMake option was added (#49) to allow using the vulkan headers from the installed SDK instead of the ones shipped with Anvil, which is great, but Anvil still always uses the shipped version of _glslang_ instead of the SDK version.
Since the _glslang_ library is part of the vulkan SDK anyway, I think the CMake option should probably also make it so the SDK version is used instead of the shipped version, or there should be an additional CMake option for that.

// Edit:
In fact, it's a bit of a source of confusion right now. I originally assumed that _ANVIL_USE_BUILT_IN_VULKAN_HEADERS_ referred to ALL headers from the SDK (including _glslang_ and _spirv-tools_), so I linked against the SDK versions of those libraries. Since the SDK version differed from the Anvil version, that didn't go so well.

**Comment by DominikWitczakAMD** [comment]
Addressed internally. Anvil's CMake file now includes a new ANVIL_USE_BUILT_IN_GLSLANG option which is enabled by default. If it is disable, a new ANVIL_GLSLANG_PATH option will allow apps to specify an alternative location to use as glslang's root directory.

**Comment by DominikWitczakAMD** [comment]
Fixed in the latest version.
