### ISSUE TITLE
Unhandled VK_ERROR_OUT_OF_DATE_KHR when Anvil-based program with window is minimized with Nvidia drivers

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#132]
This happens for example when running the _MultiViewport_ demo with a Nvidia GPU, and then minimizing the window. (Tested with a Nvidia GTX 650 Ti BOOST)
The reason is that _vkQueuePresentKHR_ in _Queue::present_internal_ returns _VK_ERROR_OUT_OF_DATE_KHR_, which isn't being handled by Anvil.

I'm not sure whether to consider this a bug, I guess it's more of a feature request? I think it would make sense for Anvil to handle this case.

**Comment by DominikWitczakAMD** [comment]
The out-of-date error was actually one of the reasons Anvil::Queue::present_internal() has had <out_present_results_ptr> added. :-)

We could theoretically have Anvil re-create the swapchain behind the curtains. However, this is something I'd rather have apps handle this event explicitly. I'm also worried about implications of the app ignoring the fact the swapchain is no longer functional.

Anvil has been proven to correctly handle use cases where app recreates the swapchain. One of the projects I'm aware of that does this is VKGL (https://github.com/kbiElude/VKGL ).

**Comment by DominikWitczakAMD** [comment]
One more reason I'm against handling this event at library level is my past experience with deferred baking. When Anvil started, a lot of things would be sneakily handled by the library. This resulted in all sorts of side effects it took me quite some time to get right, in most cases by getting rid of the said mechanism. I'd rather not take that path again.

**Comment by DominikWitczakAMD** [comment]
Assuming we reached an agreement :) Please feel free to reopen the issue if we need to rediscuss this.
