### ISSUE TITLE
Assertion failure when using specialization constants

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#134]
Every time I try to use specialization constants, I get an assertion failure in
```Anvil::StructChainer<VkPipelineShaderStageCreateInfo>::store_helper_structure<VkSpecializationInfo>```:

**File Name:** "...\\anvil\\include\\misc\\struct_chainer.h"
**Line:** 148
**Message:** "m_structs.size() >= in_referring_struct + in_referring_struct_pnext_ptr_offset + sizeof(void*)"

I added a simple test case to the **PushConstants** demo to replicate the issue:
[specialization_constant_test.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/files/2685890/specialization_constant_test.zip)
I've marked all the lines I've changed from the original demo with the comment "// Specialization constant test".
I'm on the latest version (git) of Anvil.

**Comment by DominikWitczakAMD** [comment]
Confirmed, this is a legitimate bug. I've fixed this internally. The patch will be included in next week's release.
