### ISSUE TITLE
Crash when submitting queue on Nvidia GPUs

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#142]
This is a new bug which was introduced in one of the recent Anvil updates. I'm unsure which update introduced it, but I've tested it with an old version I pulled from the repository on the 18-11-30, and that still worked, so it must've been something that was changed/added after that.

To replicate the bug, simply run the "OutOfOrderRasterization" demo with a **Nvidia GPU** installed (some of the other demos will cause the same problem). The crash will occur in _Anvil::Queue::submit_, right after the _Anvil::Vulkan::vkQueueSubmit_-call. Validation layers do not print any warnings or errors. The only error message is this:

> Exception thrown at 0x69A261E6 (nvoglv32.dll) in OutOfOrderRasterization.exe: 0xC0000005: Access violation reading location 0x00000034.

**Comment by DominikWitczakAMD** [comment]
Whoops, wasn't intending to drop the issue. Please confirm the latest version solves the issue you're seeing on your end and close the ticket if the bug no longer reproduces.

**Comment by Silverlan** [comment]
Thank you, I gave the latest version a try and that seems to have resolved the issue!
