### ISSUE TITLE
device Transfer queue uses compute queue size

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-LibrariesAndSDKs/Anvil#2]
When asking for a transfer queue, it checks the compute queues size (cut and paste error). 
For a card that doesn't have compute queues this incorrectly fails when asking for transfer queue.

Attached is patch that fixes it (also adds an assert for similar errors in future)

[Found_and_fixed_bug_in_Anvil_transfer_queues.patch.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/files/327826/Found_and_fixed_bug_in_Anvil_transfer_queues.patch.txt)

**Comment by DominikWitczakAMD** [comment]
Thank you very much for the contribution, it's clearly a bug. We'll have it fixed for the next Anvil release.

**Comment by DominikWitczakAMD** [comment]
Fixed internally, closing.
