### ISSUE TITLE
Compilation with VS2017 produces too many warnings

### ISSUE THREAD

**Issue by realvictorprm** [GPUOpen-LibrariesAndSDKs/Anvil#22]
Hello developers,

I'm using Visual Studio 2017 to compile Anvil and noticed that the compilation produced about 4000 warnings. Some of the warnings are for example due to _warning C4571_. 
_So in short, there are some VS 2017 compatibility problems._

In comparison to VS2015 compilation on the same computer with no warnings being produces I guess there's something wrong.

PS: Sorry for this less information. I try to find out more and I'll edit the issue but currently it's only notice.

**Comment by DominikWitczakAMD** [comment]
This will be addressed in next week's update.

**Comment by DominikWitczakAMD** [comment]
Should be fixed now. Please reopen if you run into any issues.
