### ISSUE TITLE
Allow usage of existing window

### ISSUE THREAD

**Issue by julianko** [GPUOpen-LibrariesAndSDKs/Anvil#25]
It would be nice to have a way to create an Anvil::Window from an existing WindowHandle/XCB connection.

That way one could use Anvil::Swapchain with an SDL window, which is not possible currently (as far as I can see?).

**Comment by DominikWitczakAMD** [comment]
Sounds like a good idea. I'll try adding this feature in the coming minor update, which should land later this week.

**Comment by DominikWitczakAMD** [comment]
Please have a look at the latest version. You should now be able to create Window wrapper instances by passing HWND handles.

That being said, I need to stress we don't really have any internal use cases for the new functionality right now , so it hasn't been tested much, other than by doing a careful code review. I'd appreciate if you could give it a whirl, see if it works as expected and - if not - propose a PR with the relevant fixes.

**Comment by julianko** [comment]
I'll take a look at it, thank you!
