### ISSUE TITLE
Unexpected - Sample Mask always on even when not used

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#29]
Hey Dominik,

Ran into a "Oh dear - didn't expect that" situation.

The "sample mask" for MSAA is always-on, even if it's not wanted (for example, when 0 is written to it). This resulted in me ending up with a blank screen when I enabled MSAA because every single sample was masked out.

I believe the culprit is in graphics_pipeline_manager.cpp, line #636:
```multisample_state_create_info.pSampleMask           = &current_pipeline_config_ptr->sample_mask;```

According to Vulkan Spec, this needs to be "NULL" if you're not going to use a sample mask.

To be inline with the rest of the pipeline manager features, probably the right solution is to create a method to enable/disable the Sample Mask (disabled by default), and set this to NULL if it's disabled.

**Comment by DominikWitczakAMD** [comment]
Sounds good! Do you have the bandwidth to propose a pull request, or are you OK to wait till the next week's update?

**Comment by DominikWitczakAMD** [comment]
Sorry, I haven't had time recently to watch any newly opened issues on GitHub and this has fallen off my radar. I'll patch this up for the next week's update.

**Comment by marti4d** [comment]
Thanks Dominik. I *will try* to help with some of these if I can find the cycles, but the project I'm on right now is really tight time-wise so unfortunately I've mostly just been dumping them without helping much :(

**Comment by DominikWitczakAMD** [comment]
I hear you ;) ..

**Comment by DominikWitczakAMD** [comment]
Fixed internally. The upcoming update will address this issue.

Just to double-check: I'm assuming you had been passing a value of 0 via the sample_mask argument when invoking Anvil::GraphicsPipelineManager::set_multisampling_properties(), assuming it wouldn't matter since you had not explicitly enabled the sample mask mode, correct?

**Comment by DominikWitczakAMD** [comment]
The latest version contains the requested improvements.
