### ISSUE TITLE
Redesign Subpass/Pipeline Distinction

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#31]
It seems from the API that Anvil has a few strange interactions between Subpasses and Pipelines.

For example, the `Anvil::RenderPass::add_subpass()` method takes pointers to all the shader stages, even though this is a property of a Pipeline. If you don't pass in a PipelineID, it will create one for you with these shader stages, but if not then it will ignore these arguments.

The subpass also stores a pointer to a single pipeline that can be set and retrieved with `get_subpass_graphics_pipeline_id()` and `set_subpass_graphics_pipeline_id()`. But a subpass can and often will have more than one pipeline associated with it, since this is how different materials are usually handled. So I don't know that it makes sense for there to be a 1-to-1 mapping like this.

It seems like there may also be a circular dependency in the API - If I try to create a pipeline through the `GraphicsPipelineManager`, it requires the ID of the subpass I want to create it for. 

BUT if I want to create a Subpass via `RenderPass::add_subpass()`, it requires a PipelineID if I don't want to just create the default.

So it seems like the only choice the API gives is to use the default pipeline that is created automatically by `add_subpass()`

I think probably the best course of action overall is to just leave it to the user of the API to create their own pipelines manually. Even when I was first using the API, it seemed like somewhat of an counter-intuitive side-effect that the `add_subpass()` method went into the GraphicsPipelineManager and added a GraphicsPipeline on my behalf.

**Comment by DominikWitczakAMD** [comment]
Fixed internally - subpasses are no longer associated with specific graphics pipelines. Sorry about this!

The fix will be coming in the first week of January's drop.

**Comment by DominikWitczakAMD** [comment]
Addressed in the update I've just pushed and will merge into master once all automated builds complete.
