### ISSUE TITLE
Use std::function instead of C-style Callback/UserPtr mechanism

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#33]
I believe there are a few places this is done in Anvil (Keypress callbacks, validation callbacks, window drawFrame callbacks), but C++11 introduced [std::function](http://en.cppreference.com/w/cpp/utility/functional/function) to STL, which creates a typesafe alternative to the old, type-unsafe, memory-leaky, C-style callback mechanism of passing a "Function Pointer + (void* userArgs)" pair and holding your nose while you use `reinterpret_cast<>`. It also accepts Functors, Lambda Expressions, Pointer-to-member-functions, etc, which are starting to become much more prominent in modern C++ code.

It would be nice down-the-road to see all instances of callbacks used in Anvil to adopt this newer mechanism.

**Comment by DominikWitczakAMD** [comment]
That's a good suggestion, thanks! Will look into implementing this in one of the future updates.

**Comment by DominikWitczakAMD** [comment]
Addressed internally. Will be included in the next week's update.
