### ISSUE TITLE
Automatic Baking is Tricky

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#34]
Just more-or-less opening this topic for possible debate - But so far I have been burned quite a few times in Anvil because I did not understand the (somewhat unexpected) things that will silently cause a bake to happen. 

For example, the following code won't work, even though it looks like it should (Arguments simplified for clarity)

```
// Create an allocator and use it for both color and depth attachment images

pAllocator = Anvil::MemoryAllocator::create_oneshot();

pColorImage = Anvil::Image::create_nonsparse();

pAllocator->add_image_whole(pColorImage);

pColorImageView = Anvil::ImageView::create_2D(pColorImage);

pDepthImage = Anvil::Image::create_nonsparse();

pAllocator->add_image_whole(pDepthImage ); // Won't work - Creating pColorImageView silently baked this one-shot allocator

pDepthImageView = Anvil::ImageView::create_2D(pDepthImage);

```

I think there are a few ways to make it more clear that wrapping an Image in an ImageView will bake the allocator:

1) Easiest perhaps would just be to require the user to call `bake()` explicitly. This at least provides a hint in the code that the one-shot allocator has been used. Now the code would look like this:

```
pAllocator = Anvil::MemoryAllocator::create_oneshot();

pColorImage = Anvil::Image::create_nonsparse();

pAllocator->add_image_whole(pColorImage);

pDepthImage = Anvil::Image::create_nonsparse();

pAllocator->add_image_whole(pDepthImage ); 

pAllocator->bake(); // Now at-least looking at the code, I may deduce that I shouldn't rearrange the code above or below this line

pColorImageView = Anvil::ImageView::create_2D(pColorImage);

pDepthImageView = Anvil::ImageView::create_2D(pDepthImage);
```

2) IMHO the "gold standard" way to do it would be to treat the allocator more like a "builder" - Add the descriptions of all the images and buffers that are assigned to it into a list. Then the user has to call "bake()", which would then actually create-and-allocate the usable Image and Buffer objects and allow the user to retrieve them.

In the second example, the above code may look more like this:

```
pAllocator = Anvil::MemoryAllocator::create_oneshot();

colorImageId = pAllocator->add_image_nonsparse(...);
depthImageId = pAllocator->add_image_nonsparse(...);

pBakedAllocator = pAllocator->bake();

// It is now impossible for me to create the ImageViews without a BakedAllocator/ImageId pair
pColorImageView = Anvil::ImageView::create_2D(pBakedAllocator, colorImageId);
pDepthImageView = Anvil::ImageView::create_2D(pBakedAllocator, depthImageId );
```

I don't know if there are other ideas on how to remove some of the footguns from this process, or if it's even worthwhile to change it. The answer might very-well just be, "This is C++ - Learn to RTFM".

**Comment by DominikWitczakAMD** [comment]
I see what you mean. Deep down, it looks as if writing down a list of cases which trigger baking would resolve this issue. In this particular case, Vulkan spec requires a fully-resident image to have a physical memory backing assigned before an image view can be created. This leads to baking op happening at first image view's creation time, and later leads to the failure when you try to create a second image view.

There's two solutions for this problem:

1) Switch to the VMA allocator which supports unlimited number of bake operations. It uses a different back-end (and a separate library to handle memory fragmentation issues), which is not as extensively tested though.
2) Introduce a new "require_explicit_bake" argument you'd need to pass at one-shot allocator creation time, which - when set to true - would prevent the baking operation from kicking in if necessary.

Does 2) sound like a useful tool for your needs?

**Comment by DominikWitczakAMD** [comment]
No longer relevant as we have had VMA support for a long time now.
