### ISSUE TITLE
Compile warnings when building without window system support

### ISSUE THREAD

**Issue by FibHeap** [GPUOpen-LibrariesAndSDKs/Anvil#35]
If both CMake options  `ANVIL_INCLUDE_WIN3264_WINDOW_SYSTEM_SUPPORT `and `ANVIL_INCLUDE_XCB_WINDOW_SYSTEM_SUPPORT` are set to OFF the build on (Visual Studio 2017 Win64) fails with a warning that the switch in RenderingSurface::init has no "case"es.

If the above warning is fixed, the goto in the switch default creates "unreachable code" warnings.

I am interested in rendering off screen on a server. Is it not correct to set both CMake variables to OFF?

**Comment by DominikWitczakAMD** [comment]
Apologies for the late delay, I've been swampled with various stuff. The use case you described should be supported without any warnings generated during compilation.

Let me look into this right now and see if this has already been fixed internally or needs to be addressed. Will get back to you shortly.

**Comment by DominikWitczakAMD** [comment]
Turns out this bug has been addressed internally some time ago. I'll do my best to push out an update today which should resolve this issue.

**Comment by DominikWitczakAMD** [comment]
The latest version should address this issue. Please re-open this ticket if you find this still bug continues to affect your application.
