### ISSUE TITLE
Use std::string Across the Board in API

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#37]
This is mostly good, but there are a couple of spots where I am still forced to use the ".c_str()" function to pass a C-style string to Anvil.

One such example is `Anvil::ShaderModule::set_name()`, but there are others.

Just documenting this for the future as part of generic API cleanup.

**Comment by DominikWitczakAMD** [comment]
Thanks for spotting this. Will fix this in one of the coming updates.

**Comment by DominikWitczakAMD** [comment]
Addressed internally. Relevant changes will be released in the update next week.
