### ISSUE TITLE
Reimplement Windows Message Pump

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#39]
Currently, Anvil's main loop uses the Windows command `GetMessage()` to dispatch messages to the window procedure, and intercepts the `WM_PAINT` message to draw.

This is not the intended use of `WM_PAINT`, which is meant to be used for the Windows GDI with the `ValidateRect()` and `InvalidateRect()` calls to update the client's area back when Windows was still using a stacking window manager.

The only reason this works properly right now is because Anvil does not properly handle the `WM_PAINT` call, which forces Windows to send it to the app window over-and-over again in hopes that the app will eventually paint its window properly.

Anvil's loop should likely switch to a message pump that looks kind-of like [this](http://www.directxtutorial.com/Lesson.aspx?lessonid=9-1-4) (Except I would put the check for `WM_QUIT` in the `while(PeekMessage(...))` loop)

And `WM_PAINT` should probably just be ignored and passed off to the default window procedure (which will just validate the entire client area, stopping future WM_PAINT messages)

**Comment by DominikWitczakAMD** [comment]
Thanks for spotting this. I will be modifying related logic in the coming weeks, so this issue should hopefully be addressed fairly quickly (though changes they will make it to the public repo this week are very scarce).

**Comment by DominikWitczakAMD** [comment]
Actually, this one proved to be trivial to fix :-) Addressed internally already, so the patch will be included in the coming update.
