### ISSUE TITLE
Minor compile fix

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-LibrariesAndSDKs/Anvil#4]
In src/wrappers/memory_block.cpp Line 9 nullptr is used rather than VK_NULL_HANDLE which is required for windows build.

Attached is a 1 line diff

[anvil_null_fix.diff.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/files/403466/anvil_null_fix.diff.txt)

**Comment by DominikWitczakAMD** [comment]
Thanks for spotting & reporting this issue :-) We're going to patch it for the next release.

**Comment by DominikWitczakAMD** [comment]
Addressed internally. Please re-open if you spot the problem in the next release.
