### ISSUE TITLE
Null Pointer Check Misses Null Pointer

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#41]
From `queue.cpp`, line #233:
```
    if (in_swapchain_ptr != nullptr)
    {
    ...
    }
    swapchains_vk[0] = in_swapchain_ptr->get_swapchain_vk();
```

`in_swapchain_ptr` is used regardless of whether the null check passes or not.

**Comment by DominikWitczakAMD** [comment]
I've added an assertion check internally to guard against nullptr in_swapchain_ptr ptrs. This will later be combined with new critical assertion checks (which you suggested in a different ticket) which are going to abort execution if the specified condition is not met, ultimatelly guaranteeing a NPE will not occur in release builds.

**Comment by DominikWitczakAMD** [comment]
I'm going to assume the proposed solution works for you for now. Once Anvil switches to "normal" and "critical" assertion checks, the new assertion check should completely guard against the potential NPE you discovered
