### ISSUE TITLE
Anvil build creates 'config.h' in source tree, not build tree

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#47]
I haven't investigated yet (if I get a chance, I'll update further), but I've noticed that Anvil creates `include/config.h` in the source tree instead of the build tree. This is probably not the desired behavior, and leads to a bit of an annoyance because Git wants me to add the file even though it's generated.

**Comment by DominikWitczakAMD** [comment]
Fixed internally. This change will be included in the coming update.

**Comment by DominikWitczakAMD** [comment]
The latest version contains a fix for this issue. Thanks for reporting.
