### ISSUE TITLE
Framebuffer::add_attachment compares image view height with framebuffer layersCount

### ISSUE THREAD

**Issue by FibHeap** [GPUOpen-LibrariesAndSDKs/Anvil#48]
For layered rendering one wants to attach a layered 2D image view to a layered framebuffer. 
The base mipmap level of such an image view is W x H x 1. This dimensions is seems to be compared to W x H and **layers** of the framebuffer. 

framebuffer.cpp:152
```
 if (view_size[0] < m_framebuffer_size[0] ||
     view_size[1] < m_framebuffer_size[1] ||
     view_size[2] < m_framebuffer_size[2])
 {
     /* Attachment size is wrong */
     anvil_assert_fail();

    goto end;
 }
```

**Comment by DominikWitczakAMD** [comment]
Apologies, haven't gotten to this yet. I will address this in the coming update.

**Comment by DominikWitczakAMD** [comment]
A fix for this has been included in the recent update.
