### ISSUE TITLE
Don't ship vulkan.h in the source code

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#49]
Ouch - got burned by this when I couldn't figure out why my code wouldn't compile after installing the latest Vulkan SDK on my machine, which has new structures and enums I need.

`vulkan.h` is checked in under `Anvil/include/vulkan`, and Anvil prefers to use that instead of the one from the Vulkan SDK on the machine.

IMHO Anvil should probably just use whatever SDK is installed on the machine. If there isn't one, having CMake give the old "Computer says no" seems like the right thing to do ;)

**Comment by DominikWitczakAMD** [comment]
We've got some internal needs, for which this header is a part of Anvil, but I see your point. Would adding an option to CMake which would let you specify where the Vulkan header should be taken from (i.e. VK_SDK_PATH or Anvil) solve the problem here?

**Comment by marti4d** [comment]
Hmmm... I suppose that would fix the problem, although it seems weird to include things that are required as part of AMD internal infrastructure in an open-source project?
