### ISSUE TITLE
ANVIL_KEY_HELPER  and KeyID aren't part of the library

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-LibrariesAndSDKs/Anvil#5]
In types.h there are types related to keyboards, that aren't really part of Vulkan. Should probably moved to another header, as some Vulkan platforms might not have keyboards going forward.

**Comment by DominikWitczakAMD** [comment]
Sorry for getting back to you so late. Since I don't have any strong feelings about this, I'll just go and move these types to a separate header.

This change will be included in the next Anvil update.
