### ISSUE TITLE
It is almost meaningless to use VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT as the srcStageMask in a barrier

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#51]
In Image.h, there are 2 spots where pipeline barriers are used:

- To transition the image to "transfer dest" format so the mipmap data can be transferred to it
- To transition the image to its final layout once that's done

In both situations, Anvil currently uses `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` as the srcStageMask. Unfortunately, doing this doesn't accomplish anything. According to the Vulkan Spec:

```
An execution dependency with only VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT in the 
destination stage mask will only prevent that stage from executing in subsequently 
submitted commands. As this stage does not perform any actual execution, this is not 
observable - in effect, it does not delay processing of subsequent commands. Similarly an 
execution dependency with only VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT in the source stage 
mask will effectively not wait for any prior commands to complete.

When defining a memory dependency, using only VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT 
or VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT would never make any accesses available and/or
 visible because these stages do not access memory.
```

The validation layers also complain about it with the following message:

```
[!] vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x5000) is not supported 
by srcStageMask (0x1). The spec valid usage text states 'Each element of 
pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any 
access flag included in its srcAccessMask member if that bit is not supported by any of the 
pipeline stages in srcStageMask, as specified in the table of supported access types.' 
(https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html
#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
```

I believe that it is okay to do this for the first barrier, since there is no dependency since the image is new and has never been used before, but the one that transitions to final layout definitely needs to be fixed.

**Comment by marti4d** [comment]
My suggestion for the change, which seems to work on my machine.

For the transition to final image layout:

```C++
srcStageMask = VK_PIPELINE_STAGE_HOST_BIT | VK_PIPELINE_STAGE_TRANSFER_BIT;
srcAccessMask = VK_ACCESS_HOST_WRITE_BIT | VK_ACCESS_TRANSFER_WRITE_BIT;

dstStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
dstAccessMask = VK_ACCESS_SHADER_READ_BIT; // Determined by Anvil from final image layout
```

Read this as "Any host writes or transfer writes must be complete and visible before the transition starts, and the transition must be completed before any stage anywhere accesses this image as a readable texture"

**Comment by DominikWitczakAMD** [comment]
I believe this has been addressed in the recent update. Can you have a look when you get a free sec, please? Thanks.

**Comment by DominikWitczakAMD** [comment]
Assuming this issue has been resolved. Please re-open if you disagree.
