### ISSUE TITLE
Update readme.md to More Properly Reflect Reality of using Anvil

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#52]
In the `readme.md` file shipped with Anvil, the following claim is made:

```
You are free to use any of its parts you like, and write your own code for everything else. 
Any Anvil wrapper for an actual Vulkan object can be queried to retrieve the raw 
Vulkan handle.
```

I think that this claim is **somewhat misleading** for a developer that is window-shopping for a library or framework to use in their code. The following 2 points make it very difficult to mix raw Vulkan objects with Anvil objects:

1. The Anvil classes are mostly designed to be used only with other Anvil classes, and don't take raw Vulkan handles as arguments for almost any of their functionality.
2. If the user uses the raw Vulkan handles returned by Anvil, they risk causing the Vulkan state to go out-of-sync with the Anvil state, leading to all kinds of undefined behavior

So creating your own Vulkan objects and trying to use them in Anvil is **not possible**, and having Anvil create your objects and then trying to use them with the Vulkan API is **often dangerous**.

I feel that this part of the readme should be updated to indicate that if somebody decides to use Anvil, they're all-in for strictly using Anvil - There doesn't really exist some half-measure where they can dip their toe in the water, or workaround missing functionality.

**Comment by DominikWitczakAMD** [comment]
Fixed in one of the recent updates.
