### ISSUE TITLE
Change supported NT version to something more reasonable

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#54]
From `Anvil/include/misc/types.h`:

```
#define ANVIL_MIN_WIN32_WINNT_REQUIRED 0x0400
```

4.0 is the kernel for "Windows NT 4.0", an operating system that was released in 1996. I am fairly certain that Anvil and Vulkan will not work on such a machine (nor should it honestly try to :-S )

I suggest to set this to something a bit more reasonable - Windows XP would be 5.1, but I'm guessing that the earliest OS that Anvil is realistically tested on is probably Windows 7, which would be NT version 6.1

PS:

_The reason I care about this is because I'm using the RawInput API, which is not available before Windows XP, and I couldn't figure out for a while why the symbols I needed weren't available while using Anvil_

**Comment by DominikWitczakAMD** [comment]
Bumped the #define to 0x0501. We do use this library in software that is executed in Windows 7. :-)

**Comment by DominikWitczakAMD** [comment]
As usual, the change is going to be included in the coming update.

**Comment by DominikWitczakAMD** [comment]
The latest version contains the fix for this issue. Thanks for reporting.
