### ISSUE TITLE
Binding arrays very difficult to use

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/Anvil#55]
`Anvil::DescriptorSetGroup::set_binding_array_items()` expects an array of `BindingElementType` values.

However - Due to some unfortunate design choices, creating such an array dynamically is very difficult. Since there is no default constructor and no copy constructor, the entire array must be initialized with known values upon creation. That's obviously not possible when the count isn't known until runtime.

So far, the only workaround I've got for this is to use placement new(), but that's really quite a pain.

Suggested fix is either to enable the default constructor and copy operator (being careful of the pitfalls of doing so with inheritance), or else change `set_binding_array_items()` to take an array of pointers instead so the objects can be created dynamically.

**Comment by DominikWitczakAMD** [comment]
Useful observation, thanks. If you have the bandwidth, I'd like to encourage you or anyone else reading this to propose a patch for this issue.

I'm currently working on adding MT safety to Anvil; it's done already but a few things such as deferred pipeline and DSG baking proved not to work correctly unless I add a nasty workaround which is impractical. Clearing up this situation is going to require doing a number of changes on the architecture level. So once I'm done with that and still riding the "woohoo, let's flip the existing design table" tide, I'm probably going to look into solving the issue you reported here.

**Comment by DominikWitczakAMD** [comment]
Addressed internally by adding a new version of set_binding_array_items() that takes a const BindingElementType* const* in_elements argument to both Anvil::DescriptorSet and Anvil::DescriptorSetGroup classes.

The fix will be included in the coming update.

**Comment by DominikWitczakAMD** [comment]
Hopefully addressed with the latest version. Please give it a shot and feel free to re-open the issue if you have further observations. Thanks.
