### ISSUE TITLE
Where's the example?

### ISSUE THREAD

**Issue by Delwin9999** [GPUOpen-LibrariesAndSDKs/Anvil#6]
The readme mentions an example but it is not in this repository.  Can you check it in please?

**Comment by DominikWitczakAMD** [comment]
The example can be found under https://github.com/GPUOpen-LibrariesAndSDKs/OutOfOrderRasterization. I have to admit the current separated model can be confusing. I'll see what we can do to improve this.

**Comment by jstewart-amd** [comment]
Previously, the OutOfOrderRasterization sample was in a separate repo. We have now moved it under the examples folder in the Anvil repo.

@DominikWitczakAMD has also created four new samples.
