### ISSUE TITLE
Suggestion: Switch to vulkan.hpp

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#65]
Anvil is C++ only anyway, so I don't see much of a reason to stick to the C-header. Most C++-programmers (including me) would probably be more comfortable with the provided type safety of vulkan.hpp.

**Comment by DominikWitczakAMD** [comment]
I'm on the fence with this problem.

On one hand, I agree the proposed solution introduces useful type safety and other benefits stemming from the fact C is no more.

On the other hand, the ask here really seems to be to drop any locations in Anvil where programmers need to pass raw Vulkan structure and enums, and instead have them pass Anvil-specific type-safe values. Is my understanding correct?

Admittedly, oldschool C enums that are still used in some areas of Anvil are a pain and a source of endless bugs, and we should move to fixed-type enums instead. The migration has actually happened some time ago but the pace has been mediocre, to say the least. Getting this resolved is on my TODO list.

Are there any other things in Anvil you're finding too C-like, which - when addressed - would improve your user experience? Thanks.

**Comment by DominikWitczakAMD** [comment]
Type safety is now enforced in Anvil.
