### ISSUE TITLE
Copy constructor of BufferBindingElement does not copy size and start offset

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#66]
The copy constructor for _BufferBindingElement_ (src/wrappers/descriptor_set.cpp) looks like this:
```
Anvil::DescriptorSet::BufferBindingElement::BufferBindingElement(const BufferBindingElement& in)
{
    buffer_ptr = in.buffer_ptr;
}
```

The _size_ and _start_offset_ members should probably be copied as well.

**Comment by DominikWitczakAMD** [comment]
Thanks for spotting this! Addressed internally, the fix will land in the next week's update.
