### ISSUE TITLE
"Anvil" name conflicts with Intel's open-soure driver

### ISSUE THREAD

**Issue by jekstrand** [GPUOpen-LibrariesAndSDKs/Anvil#7]
"Anvil" (shortened to anv) is the code-name we've been using for the open-source Intel Vulkan driver for over a year.

**Comment by Elxarus** [comment]
What is your point?
Anvil was AMD's name going back over a year as well...
https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/commit/1fa7dbec2793c0035a4b7013ae84223f805d8ed5 

Microsoft also used Anvil back in 2003.

If you shorten it to anv, might as well keep calling it anv anway.

**Comment by DominikWitczakAMD** [comment]
Sorry about this, but I'm not really sure what action you're proposing us to take at this point. We're not going to change the project name at this point.

**Comment by jekstrand** [comment]
I understand.  I just wanted to make you aware of the collision if you weren't already.  I don't really expect you to change yours.  At the end of the day, it probably won't matter much as most people think of our Vulkan driver as "the Intel Linux Vulkan driver" and not "Anvil" so there shouldn't be too much confusion.

What can I say?  You've got good taste in project names. :-)
