### ISSUE TITLE
GLSLShaderToSPIRVGenerator::get_spirv_blob throws std::out_of_range exception if shader compilation or linking failed

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#70]
According to the description of _get_shader_info_log_ and _get_program_info_log_, you should be able to call _get_spirv_blob_ and check if its return value is _nullptr_ to find out whether there was a problem during compilation or linking.
However looking at the definition of _get_spirv_blob_, it looks like it can never return _nullptr_ and will throw an exception instead (or an assertion failure in debug mode):
```
const char* get_spirv_blob() const
{
    if (m_spirv_blob.size() == 0)
    {
        bool result = bake_spirv_blob();

        ANVIL_REDUNDANT_VARIABLE(result);

        anvil_assert(result);
        anvil_assert(m_spirv_blob.size() != 0);
    }

    return &m_spirv_blob.at(0);
}
```

As far as I can tell, there's no way to actually check if an error has occurred at the moment, even _get_spirv_blob_size_ would cause an assertion failure.

**Comment by DominikWitczakAMD** [comment]
This is a fair observation. I will be addressing this later next week. Also hoping I'll finally get around to posting an update next week, too!

**Comment by DominikWitczakAMD** [comment]
Addressed internally.
