### ISSUE TITLE
No way to retrieve info debug log from GLSLShaderToSPIRVGenerator

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#71]
There's _GLSLShaderToSPIRVGenerator::get_shader_info_log_, which returns the result of _glslang::TShader::getInfoLog_, however there's also a debug log (_glslang::TShader::getInfoDebugLog_), which is currently inaccessible through _GLSLShaderToSPIRVGenerator_.

**Comment by DominikWitczakAMD** [comment]
Addressed internally. The enhancement will be included in the update coming later this week.
