### ISSUE TITLE
CommandBufferBase::record_update_buffer takes a pointer to uint32_t instead of void?

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#74]
_vkCmdUpdateBuffer_ takes a _const void*_ parameter for the data, but _CommandBufferBase::record_update_buffer_ takes a _const uint32_t*_, which seems a little odd to me:
```
bool record_update_buffer(Anvil::Buffer*  in_dst_buffer_ptr,
                            VkDeviceSize    in_dst_offset,
                            VkDeviceSize    in_data_size,
                            const uint32_t* in_data_ptr);
```
The parameter should probably be _const void*_ as well.

**Comment by DominikWitczakAMD** [comment]
I believe the original intent behind in_data_ptr being a uint32_t ptr was that @param in_data_size has to be a mul of 4 as per Vulkan spec.

That being said, I agree this type goes against the original API and should be changed to const void*. Will fix this next week.

**Comment by DominikWitczakAMD** [comment]
Fixed internally.
