### ISSUE TITLE
Example can't find -lvulkan

### ISSUE THREAD

**Issue by Sumenia** [GPUOpen-LibrariesAndSDKs/Anvil#8]
Hi,

In the CMakeLists of the examples, on linux build you define the path to Vulkan_SDK as follow : 
```
    include_directories($ENV{VK_SDK_PATH}/x86_64/include
                        $ENV{VULKAN_SDK}/x86_64/include)
    link_directories   ($ENV{VK_SDK_PATH}/x86_64/lib
                        $ENV{VULKAN_SDK}/x86_64/lib)
```

Or, the official LunarG pre-compiled VulkanSDK define the environment variable as follow :
`export VULKAN_SDK=$PWD/x86_64`
see : https://vulkan.lunarg.com/doc/sdk/1.0.42.1/linux/getting_started.html

As a result, the linker can't find it.

edit : i agree this a minor issue, but still. I think the correct behaviour should expect the environment variable defined by LunarG SDK or provide a FindVulkan.cmake

**Comment by DominikWitczakAMD** [comment]
*sigh* Sorry about this. As you can see by what's already in CMake files, environment vars which hold the paths to the SDK were renamed at least twice over the course of SDK lifetime, and now it seems they also changed their meaning.

I'm going to patch this up internally later today. Will update this repo in the near future. Many thanks for reporting this!

**Comment by Sumenia** [comment]
May i suggest to use [CMake's FindVulkan.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake) to solve this ?

**Comment by DominikWitczakAMD** [comment]
Sounds like a good idea for improvement. I've got something else on my plate at the moment, so won't be able to look into this, so if you feel like proposing a pull request, please go ahead! :-)

**Comment by DominikWitczakAMD** [comment]
We're going to need to have the script reviewed internally before we can include it with Anvil. Until that happens, we're going to have to live with what we have.

**Comment by DominikWitczakAMD** [comment]
We fixed the issue you reported internally last week and have just upstreamed it to the public GitHub repository.

Will replace it with the script you mentioned after I get a green light.

**Comment by DominikWitczakAMD** [comment]
Anvil's CMake now uses find_library() to locate the library. The change that does this will percolate to this repository later this week.
