### ISSUE TITLE
ImageView::get_swizzle_array - required size for parameter?

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#83]
```
void get_swizzle_array(VkComponentSwizzle* out_swizzle_array_ptr) const
{
    memcpy(out_swizzle_array_ptr,
           m_swizzle_array,
           sizeof(m_swizzle_array) );
}
```
_get_swizzle_array_ copies the contents of _m_swizzle_array_ to the input array, but there's no way to know as a caller how large the input array has to be without looking into the code. The array size is always 4, but there should probably be a function to retrieve that information.

**Comment by DominikWitczakAMD** [comment]
In the latest version, swizzle array is defined as std::array<VkComponentSwizzle, 4>. I'm guessing that implicitly addresses the request?
