### ISSUE TITLE
Function definition for GraphicsPipelineInfo::get_pipeline_color_blend_attachment_state is missing

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#84]
The function is declared in _include/misc/graphics_pipeline_create_info.h_, but it doesn't seem to be defined anywhere.

As far as I can tell the function is redundant anyway, since _GraphicsPipelineInfo::get_color_blend_attachment_properties_ does more or less the same thing.

**Comment by DominikWitczakAMD** [comment]
Likely a rebase issue, as the func is not defined in our private version. Will make sure the redundant entrypoint is gone when preparing today's update.

**Comment by DominikWitczakAMD** [comment]
Sigh, this one is still in. Leaving this for the next week's update.
