### ISSUE TITLE
Debug names for BasePipelineInfo?

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#86]
The baking of a pipeline is usually delayed until that pipeline is actually used. If you have a lot of pipelines, and _Anvil::GraphicsPipelineManager::bake_ triggers an assertion failure in one of them, it can be difficult to tell which pipeline actually triggered it. For cases like that it would be handy if a debug name could be assigned to _Anvil::BasePipelineInfo_ objects, similar to how a name can be assigned to resources like _Anvil::Image_.

**Comment by DominikWitczakAMD** [comment]
Fixed internally. BasePipelineCreateInfo now exposes name accessors.
