### ISSUE TITLE
Provide meson build file?

### ISSUE THREAD

**Issue by razvan1024** [GPUOpen-LibrariesAndSDKs/Anvil#89]
I am trying to use Anvil from a meson build project. To be able to easily include Anvil I need to write a meson.build file, which would enable Anvil to be built  with meson. 

Would it be helpful if I deliver the meson.build file to the repository after I am finished?

The file would probably not allow linking with GLSLANG (as this is a dependency hell right now).

**Comment by DominikWitczakAMD** [comment]
Need to check internally. Will get back to you on this in a week or two.

**Comment by razvan1024** [comment]
Ok.

I created already the pull request, you can just reject it if the answer is no.

**Comment by DominikWitczakAMD** [comment]
Apologies for the embarrasingly long response time. I was told that contributions under Apache terms cannot be accepted for a MIT project so we cannot accept your proposal.

Sorry about this.
