### ISSUE TITLE
doesn't compile with gcc6/g++6

### ISSUE THREAD

**Issue by Sumenia** [GPUOpen-LibrariesAndSDKs/Anvil#9]
There are warnings with g++6 compiler on Linux and as -Werror is activated, it doesn't compile. 

I had to add both `-Wno-misleading-indentation` and `-Wno-strict-aliasing`  in order to silence those warnings and successfully compile.

**Comment by janisozaur** [comment]
The misleading indentation comes from external library, `miniz`. I have submitted a fix earlier to fix it upstream: https://github.com/richgel999/miniz/pull/60 and will add a PR with updated version once it gets merged.

**Comment by Sumenia** [comment]
Indeed. 
However Anvil has too some warning with g++6 that doesn't come from `miniz` such as : 
```
[ 62%] Building CXX object CMakeFiles/Anvil.dir/src/misc/page_tracker.cpp.o
/home/sumenia/Anvil/src/misc/object_tracker.cpp: In member function ‘void Anvil::ObjectTracker::check_for_leaks() const’:
/home/sumenia/Anvil/src/misc/object_tracker.cpp:66:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             ++(int&)current_object_type)
                     ^~~~~~~~~~~~~~~~~~~
```

**Comment by DominikWitczakAMD** [comment]
@Sumenia : Would you be able to provide a pull request which fixes the warnings you're seeing? We haven't stepped upon them while testing on several different compilers. Thanks!

**Comment by Sumenia** [comment]
Done.
