### ISSUE TITLE
Small error in description for CommandBufferBase::record_clear_color_image

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#94]
The description for _CommandBufferBase::record_clear_color_image_ says "It is also illegal to call this function when not recording renderpass commands.", however according to the [vulkan specs](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdClearColorImage.html) it's actually the opposite:
> This command must only be called outside of a render pass instance

Just the description is wrong, the implementation is correct.
The description for _record_clear_depth_stencil_image_ is also correct.

**Comment by DominikWitczakAMD** [comment]
Nice one!

I'll have this fixed internally in a minute. The GitHub version should see a fix coming sometime next week (yes, I'm actually intending to start pushing regular updates to the GitHub repository again!)

**Comment by DominikWitczakAMD** [comment]
Fixed internally.
