### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [GPUOpen-LibrariesAndSDKs/Anvil#96]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Anvil::GLSLShaderToSPIRVGenerator::bake_spirv_blob_by_calling_glslang](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/blob/1c75fb45372b2f7d8364d7a91c4116b3958ca4cd/src/misc/glsl_to_spirv.cpp#L675 "Anvil::GLSLShaderToSPIRVGenerator::bake_spirv_blob_by_calling_glslang function")
- [Anvil::ObjectTracker::destroy](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/blob/1c75fb45372b2f7d8364d7a91c4116b3958ca4cd/src/misc/object_tracker.cpp#L41 "Anvil::ObjectTracker::destroy function")
- [GenericPool](https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/blob/1c75fb45372b2f7d8364d7a91c4116b3958ca4cd/include/misc/pools.h#L190 "Destructor for GenericPool")

**Comment by DominikWitczakAMD** [comment]
Nice observation, thanks. Any chance you could consider contributing a merge request which would remove all the extraneous checks? Thanks!

**Comment by DominikWitczakAMD** [comment]
Fixed internally.
